# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: |
        # pip install coverage codecov
        coverage run -m pytest test_add.py --doctest-modules || true
        coverage xml
        coverage html
      continue-on-error: true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    - name: Always upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml
