name: Python application CI

on:
  push:
    branches: [ "badge-debug-sf" ]
  pull_request:
    branches: [ "badge-debug-sf" ]

permissions:
  contents: read
  # Add write permission for badges
  badges: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-md
    - name: Run tests with pytest
      run: pytest test_add.py --doctest-modules --md-report --md-report-output pytest_report.md
    - name: Create Pytest Badge
      uses: jaywcjlove/action-badges@v1.5.0
      with:
        style: flat
        label: pytest
        status: ${{ job.status }}
        icon: jest
        file: pytest-badge.svg
    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          pytest_report.md
          pytest-badge.svg