# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application CI

on:
  push:
    branches: [ "badge-debug-sf" ]
  pull_request:
    branches: [ "badge-debug-sf" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and collect coverage
      id: test
      run: |
        coverage run -m pytest test_add.py --doctest-modules || true  # Prevent failure from stopping the workflow
        echo "exit_code=$?" >> $GITHUB_ENV
        coverage xml
        coverage html
    - name: Upload coverage to Codecov
      if: always()  # Ensure this runs regardless of test results
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Always upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml
    - name: Fail the job if tests failed
      if: env.exit_code != '0'
      run: exit 1
