name: Python application CI

on:
  push:
    branches: [ "badge-debug-sf" ]
  pull_request:
    branches: [ "badge-debug-sf" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0-rc.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and collect coverage
      id: run_tests
      run: |
        pip install coverage pytest
        coverage run -m pytest test_add.py --doctest-modules
        echo "tests_exit_code=$?" >> $GITHUB_OUTPUT
        coverage xml
        coverage html
      continue-on-error: true
    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Always upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml
    - name: Check test results
      if: always()
      run: |
        if [ "${{ steps.run_tests.outputs.tests_exit_code }}" != "0" ]; then
          echo "Tests failed"
          exit 1
        else
          echo "Tests passed"
        fi